jaffle_shop:
  target: dev
  outputs:

    dev:
      dataset: dvry_corp
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: us-east1
      method: service-account
      keyfile: /secrets/dbt-service-keyfile
      priority: interactive
      project: bv-ctgd-419815458-sdx
      threads: 4
      gcs_bucket: dbt_testeintegration
      type: bigquery

    prod:
      dataset: dvry_corp
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: us-east1
      method: service-account
      keyfile: /secrets/dbt-service-keyfile
      priority: interactive
      project: bv-ctgd-419815458-sdx
      threads: 4
      gcs_bucket: dbt_testeintegration
      type: bigquery
